### ISSUE TITLE
We're going to have to use the nuclear option (lock npm/npm/issues)

### ISSUE THREAD

**Issue by smikes** [npm/support-cli#6]
I wasn't thinking clearly before when I said that closing github.com/npm/npm/issues is "to be avoided" and "the nuclear option".  It's actually a necessary step because --
# Every npm <= 2.1.9 in the wild says `npm/npm/issues` is where bug reports go

The only practical way to stop people reporting issues there is to block issue creation, or limit it to project collaborators.

I think that'll be okay, actually, provided people get enough warning about it and this new repo is up and running.  Possibly worth waiting a few weeks after all pointers **still under our control** have been updated to npm/support-cli --
- #npm irc channel title
- npm debug-log messages
- website
- documentation
- tattoos

Thoughts?  Please tell me I'm wrong about this.  I really don't like the idea; it just seems like it'll be necessary.

**Comment by othiym23** [comment]
I strongly disagree that we should block users from using npm/npm's issue tracker for support requests. We should _guide_ them here, but I'm not in favor of making people jump through hoops to communicate with us.

The primary purpose of this repository is to accept automatically generated support requests coming from `npm report`; it is _not_ the intention that we are going to force anyone to report support issues _only_ to this repo.

**Comment by smikes** [comment]
OK.  I misunderstood; I thought the goal was to get all support issues
here.  The goal you are setting is much more reasonable.
