### ISSUE TITLE
`npm report` endpoint -> direct to github or npmjs.org hosted 

### ISSUE THREAD

**Issue by smikes** [npm/support-cli#8]
I propose that the `npm report` script should send its data to some middleware on the `npmjs.org` server, which will take responsibility for creating the issue on github, creating gists and linking them, etc. etc. (possibly even adding some labels?)

The main reason I think this is worthwhile is that we want `npm report` to work for everyone without them having to log into github (some people might not have an account).  Those without accounts can't comment on their issue, but at least we'll have the initial report.

Comparison table (+ = advantage / - = disadvantage )

|  | Github | self-hosted |
| --- | --- | --- |
| up-front work | none (+) | some (-) |
| must be logged in | yes (-) | no (+) |
| client target API | 2 (issues, gists)  (-) | 1 (custom) (+) |
| stable API | probably | yes (+) |
| additional point of failure | no (+) | yes (-) |

**Comment by faiq** [comment]
Its my opinion that we should keep `npm report` self hosted. For one thing, how will the endpoint associate the correct user with the correct issue? If it's done through npm usernames, that won't work in my case because I'm different on both networks. Also, it seems like they have to login _somewhere_ either `npm` for the middleware or github for the self hosted thing.

**Comment by othiym23** [comment]
You have to have a GitHub account to file issues today, so I don't think that's an onerous obligation to place on people. We can also design `npm report`, when the time comes, to post an anonymous gist if people are submitting errors from environments (such as production servers) where it's unreasonable to expect users to be logged in.

I agree with @faiq – keeping this self-hosted will make for a much simpler user experience, at the cost of some small additional implementation and maintenance complexity.

**Comment by smikes** [comment]
> You have to have a GitHub account to file issues today

True, but I do not log in on the command line, just in my browser.  (I use ssh keys exclusively).  (Just remembered my other thing about this) - It would be better to allow people to `npm report` etc. without having to have an npm or github account.  It's a low barrier, but any barrier at all that can be eliminated should be, right?

3/3 for self-hosted.  Good to know.  I will close this for now and it can be unearthed once `npm report` starts to become a thing.
